const fs = require('fs');

const path = 'src/components/workspace/WidgetRenderer.tsx';
let code = fs.readFileSync(path, 'utf8');

const mapping = `
const HARDCODED_SECTIONS: Record<string, {code: string, name: string, category: string}[]> = {
  "Branch Lines (MKLI-GRHI)- 57 stations": [
    { code: "MKLI", name: "Makrauli", category: "HG-3" },
    { code: "JSS", name: "Jasia Halt", category: "HG-3" },
    { code: "RKX", name: "Rukhi Halt", category: "HG-3" },
    { code: "BASN", name: "Bhainswan", category: "HG-3" },
    { code: "GHNA", name: "Gohana", category: "NSG-6" },
    { code: "MDLA", name: "Mudlana", category: "NSG-6" },
    { code: "DHRN", name: "Dhurana", category: "HG-3" },
    { code: "IRA", name: "Israna Halt", category: "HG-3" },
    { code: "NLH", name: "Naultha", category: "NSG-5" },
    { code: "BNJL", name: "Binjhol", category: "HG-3" },
    { code: "ASAN", name: "Asan", category: "HG-3" },
    { code: "MLDE", name: "Madlauda", category: "NSG-6" },
    { code: "KSDE", name: "Karsindhu Halt", category: "HG-3" },
    { code: "SFDE", name: "Safidon", category: "NSG-6" },
    { code: "SXE", name: "Sila Kheri", category: "HG-3" },
    { code: "BKDE", name: "Budha Khera", category: "HG-3" },
    { code: "PKDE", name: "Pilu Khera", category: "NSG-6" },
    { code: "SPBK", name: "Sundarpur Barah Kalan", category: "HG-3" },
    { code: "SWDE", name: "Siwaha", category: "NSG-6" },
    { code: "PPDE", name: "Pandu Pindara Halt", category: "HG-2" },
    { code: "JCY", name: "Jind City", category: "NSG-6" },
    { code: "KURN", name: "Khukhrana", category: "NSG-6" },
    { code: "NARA", name: "Nara Halt", category: "HG-3" },
    { code: "GKG", name: "Gokalgarh", category: "HG-3" },
    { code: "PLHW", name: "Palhawas", category: "HG-3" },
    { code: "MHRI", name: "Machhrauli", category: "HG-3" },
    { code: "JHJ", name: "Jhajjar", category: "NSG-6" },
    { code: "DGHL", name: "Dighal", category: "HG-3" },
    { code: "BRNI", name: "Barwasni Halt", category: "HG-3" },
    { code: "MOHR", name: "Mohana Haryana", category: "HG-3" },
    { code: "LATH", name: "Lath Halt", category: "HG-3" },
    { code: "RBHR", name: "Rabhra Halt", category: "HG-3" },
    { code: "KHDR", name: "Khandrai Halt", category: "HG-3" },
    { code: "BUTN", name: "Butana Halt", category: "HG-3" },
    { code: "ISRI", name: "Ishapur Kheri Halt", category: "HG-3" },
    { code: "BHMW", name: "Bhambhewa", category: "HG-3" },
    { code: "LTKR", name: "Lalit Khera Halt", category: "HG-3" },
    { code: "TNDE", name: "Thanesar City", category: "NSG-6" },
    { code: "PDS", name: "Pindarsi Halt", category: "HG-3" },
    { code: "PBJM", name: "Pabnawa Jasmohinder", category: "HG-3" },
    { code: "PHWR", name: "Pehowa Road", category: "NSG-6" },
    { code: "TIK", name: "Tik", category: "NSG-6" },
    { code: "GXG", name: "Geong Halt", category: "HG-3" },
    { code: "NKLE", name: "New Kaithal Halt", category: "HG-3" },
    { code: "KLE", name: "Kaithal", category: "NSG-5" },
    { code: "QTP", name: "Qutabpur", category: "HG-3" },
    { code: "SJM", name: "Sajuma", category: "NSG-6" },
    { code: "KIY", name: "Kalayat", category: "NSG-6" },
    { code: "GRZ", name: "Gurthuri", category: "HG-3" },
    { code: "DBHL", name: "Dobh Bahali", category: "NSG-6" },
    { code: "SRBH", name: "Shahid Ramphal Balhara", category: "HG-3" },
    { code: "MKMN", name: "Mokhra Madina", category: "NSG-6" },
    { code: "KRKH", name: "Kharkara Halt", category: "HG-3" },
    { code: "BABH", name: "Bahalba Halt", category: "HG-3" },
    { code: "MAHM", name: "Meham", category: "NSG-6" },
    { code: "MLKN", name: "Mundhal Kalan", category: "NSG-6" },
    { code: "GRHI", name: "Garhi", category: "NSG-6" },
  ],
  "DEE Section (NDLS-STKW)- 22 stations": [
    { code: "NDLS", name: "New Delhi", category: "NSG-1" },
    { code: "DSB", name: "Delhi Sadar Bazar", category: "NSG-5" },
    { code: "DKZ", name: "Delhi Kishanganj", category: "NSG-5" },
    { code: "DEE", name: "Delhi Sarai Rohilla", category: "NSG-2" },
    { code: "DBSI", name: "Daya Basti", category: "NSG-6" },
    { code: "PTNR", name: "Patel Nagar", category: "NSG-6" },
    { code: "DEC", name: "Delhi Cantt.", category: "NSG-3" },
    { code: "PM", name: "Palam", category: "NSG-5" },
    { code: "SMDP", name: "Shahbad Mohammadpur", category: "NSG-6" },
    { code: "BWSN", name: "Bijwasan", category: "NSG-6" },
    { code: "GGN", name: "Gurgaon", category: "NSG-3" },
    { code: "BDXT", name: "Basai Dhankot", category: "NSG-6" },
    { code: "GHH", name: "Garhi Harsaru", category: "NSG-5" },
    { code: "PT", name: "Patli", category: "NSG-6" },
    { code: "TNJR", name: "Taj Nagar", category: "HG-2" },
    { code: "JSKA", name: "Jataula Jauri Sampka", category: "NSG-6" },
    { code: "PTRD", name: "Pataudi Road", category: "NSG-5" },
    { code: "IHP", name: "Inchhapuri", category: "NSG-6" },
    { code: "KIP", name: "Khalilpur", category: "NSG-6" },
    { code: "KWMD", name: "Kumbhawas Mundhalia Dabri", category: "HG-2" },
    { code: "FN", name: "Farrukhnagar", category: "NSG-6" },
    { code: "STKW", name: "Sultanpur Kaliawas", category: "HG-3" },
  ],
  "DUK Section (NDLS-MOY)- 34 stations": [
    { code: "NDLS", name: "New Delhi", category: "NSG-1" },
    { code: "DLI", name: "Delhi Junction", category: "NSG-1" },
    { code: "SZM", name: "Subzi Mandi", category: "NSG-4" },
    { code: "DAZ", name: "Delhi Azadpur", category: "NSG-6" },
    { code: "ANDI", name: "Adarsh Nagar Delhi", category: "NSG-5" },
    { code: "BHD", name: "Badli", category: "NSG-5" },
    { code: "KHKN", name: "Khera Kalan", category: "NSG-6" },
    { code: "HUK", name: "Holambi Kalan", category: "NSG-6" },
    { code: "NUR", name: "Narela", category: "NSG-4" },
    { code: "RDDE", name: "Rathdhana", category: "NSG-6" },
    { code: "HNN", name: "Harsana Kalan", category: "HG-3" },
    { code: "SNP", name: "Sonipat", category: "NSG-3" },
    { code: "SLKN", name: "Sandal Kalan", category: "NSG-6" },
    { code: "RUG", name: "Rajlu Garhi Halt", category: "HG-2" },
    { code: "GNU", name: "Ganaur", category: "NSG-4" },
    { code: "BDMJ", name: "Bhodwal Majri", category: "NSG-6" },
    { code: "SMK", name: "Samalkha", category: "NSG-5" },
    { code: "DWNA", name: "Diwana", category: "NSG-6" },
    { code: "PNP", name: "Panipat Jn.", category: "NSG-3" },
    { code: "BBDE", name: "Babarpur", category: "NSG-6" },
    { code: "KFU", name: "Kohand Halt", category: "HG-2" },
    { code: "GRA", name: "Gharaunda", category: "NSG-6" },
    { code: "BZJT", name: "Bazida Jatan", category: "NSG-6" },
    { code: "KUN", name: "Karnal", category: "NSG-3" },
    { code: "BZK", name: "Bhaini Khurd", category: "NSG-6" },
    { code: "TRR", name: "Taraori", category: "NSG-6" },
    { code: "NLKR", name: "Nilokheri", category: "NSG-6" },
    { code: "AMIN", name: "Amin", category: "NSG-6" },
    { code: "KKDE", name: "Kurukshetra", category: "NSG-3" },
    { code: "DHKR", name: "Dhoda Kheri", category: "NSG-6" },
    { code: "DPP", name: "Dhirpur", category: "NSG-6" },
    { code: "DHMZ", name: "Dhola Majra", category: "NSG-6" },
    { code: "SHDM", name: "Shahbad Markanda", category: "NSG-6" },
    { code: "MOY", name: "Mohri", category: "NSG-6" },
  ],
  "SMQL Section (NDLS-TPZ)- 40 stations": [
    { code: "NDLS", name: "New Delhi", category: "NSG-1" },
    { code: "DSB", name: "Delhi Sadar Bazar", category: "NSG-5" },
    { code: "DKZ", name: "Delhi Kishanganj", category: "NSG-5" },
    { code: "DBSI", name: "Daya Basti", category: "NSG-6" },
    { code: "SSB", name: "Shakurbasti", category: "NSG-4" },
    { code: "MGLP", name: "Mangolpuri", category: "NSG-6" },
    { code: "NNO", name: "Nangloi", category: "NSG-4" },
    { code: "MQC", name: "Mundka Halt", category: "HG-2" },
    { code: "GHE", name: "Ghevra", category: "NSG-6" },
    { code: "BGZ", name: "Bahadurgarh", category: "NSG-4" },
    { code: "ASE", name: "Asaudah", category: "NSG-6" },
    { code: "ROHN", name: "Rohad Nagar", category: "HG-3" },
    { code: "SPZ", name: "Sampla", category: "NSG-5" },
    { code: "ISM", name: "Ismaila Haryana", category: "NSG-6" },
    { code: "KRZ", name: "Kharawar", category: "NSG-6" },
    { code: "ABO", name: "Asthal Bohar", category: "NSG-6" },
    { code: "ROK", name: "Rohtak", category: "NSG-3" },
    { code: "SMF", name: "Samar Gopalpur", category: "NSG-6" },
    { code: "KHV", name: "Karainthi", category: "NSG-6" },
    { code: "LNMA", name: "Lakhan Majra Halt", category: "HG-2" },
    { code: "KPKI", name: "Qasimpur Kheri", category: "NSG-6" },
    { code: "BDHP", name: "Bhudpur", category: "HG-2" },
    { code: "ASAR", name: "Asara Halt", category: "HG-2" },
    { code: "AILM", name: "Ailum Halt", category: "HG-2" },
    { code: "KQL", name: "Kandhla", category: "NSG-6" },
    { code: "KZI", name: "Khandraoli Halt", category: "HG-2" },
    { code: "GLBN", name: "Gujran Balwa Halt", category: "HG-3" },
    { code: "SMQL", name: "Shamli", category: "NSG-5" },
    { code: "SLWR", name: "Silawar", category: "HG-3" },
    { code: "HIND", name: "Hind", category: "NSG-6" },
    { code: "UPRD", name: "Usmanpur Dehat", category: "HG-3" },
    { code: "HHP", name: "Harhar Fatehpur", category: "HG-3" },
    { code: "TBTN", name: "Thana Bhawan Town", category: "HG-1" },
    { code: "THBN", name: "Thana Bhawan", category: "NSG-6" },
    { code: "NNX", name: "Nanauta", category: "NSG-6" },
    { code: "SNAP", name: "Sona Arjunpur", category: "HG-3" },
    { code: "RPMN", name: "Rampur Maniharan", category: "NSG-6" },
    { code: "BNQL", name: "Bhankala", category: "HG-3" },
    { code: "JDHH", name: "Jandhera Halt", category: "HG-3" },
    { code: "MNZ", name: "Manani", category: "NSG-6" },
    { code: "TPZ", name: "Tapri", category: "NSG-5" },
  ],
  "SPR Section (NDLS-KZW)- 49 stations": [
    { code: "NDLS", name: "New Delhi", category: "NSG-1" },
    { code: "DSB", name: "Delhi Sadar Bazar", category: "NSG-5" },
    { code: "DKZ", name: "Delhi Kishanganj", category: "NSG-5" },
    { code: "DBSI", name: "Daya Basti", category: "NSG-6" },
    { code: "SSB", name: "Shakurbasti", category: "NSG-4" },
    { code: "MGLP", name: "Mangolpuri", category: "NSG-6" },
    { code: "NNO", name: "Nangloi", category: "NSG-4" },
    { code: "MQC", name: "Mundka Halt", category: "HG-2" },
    { code: "GHE", name: "Ghevra", category: "NSG-6" },
    { code: "BGZ", name: "Bahadurgarh", category: "NSG-4" },
    { code: "ASE", name: "Asaudah", category: "NSG-6" },
    { code: "ROHN", name: "Rohad Nagar", category: "HG-3" },
    { code: "SPZ", name: "Sampla", category: "NSG-5" },
    { code: "ISM", name: "Ismaila Haryana", category: "NSG-6" },
    { code: "KRZ", name: "Kharawar", category: "NSG-6" },
    { code: "ABO", name: "Asthal Bohar", category: "NSG-6" },
    { code: "ROK", name: "Rohtak", category: "NSG-3" },
    { code: "SMF", name: "Samar Gopalpur", category: "NSG-6" },
    { code: "KHV", name: "Karainthi", category: "NSG-6" },
    { code: "LNMA", name: "Lakhan Majra Halt", category: "HG-2" },
    { code: "KZH", name: "Kila Zafargarh", category: "NSG-6" },
    { code: "JNA", name: "Julana", category: "NSG-6" },
    { code: "JJT", name: "Jai Jai Wanti", category: "NSG-6" },
    { code: "KIU", name: "Kinana", category: "NSG-6" },
    { code: "BSPH", name: "Bishanpura Haryana", category: "NSG-6" },
    { code: "JIND", name: "Jind", category: "NSG-4" },
    { code: "BZO", name: "Barsola", category: "NSG-6" },
    { code: "GNBA", name: "Gaon Baroda", category: "HG-3" },
    { code: "UCA", name: "Uchana", category: "NSG-6" },
    { code: "GSO", name: "Ghaso", category: "NSG-6" },
    { code: "NRW", name: "Narwana", category: "NSG-5" },
    { code: "DHY", name: "Dharodi", category: "NSG-6" },
    { code: "DTN", name: "Dhamtan Sahib", category: "NSG-6" },
    { code: "KLWN", name: "Kalwan Halt", category: "HG-3" },
    { code: "TUN", name: "Tohana", category: "NSG-5" },
    { code: "HMQ", name: "Himmatpura", category: "NSG-6" },
    { code: "JHL", name: "Jakhal", category: "NSG-5" },
    { code: "KAGR", name: "Kahangarh Halt", category: "HG-3" },
    { code: "BRZ", name: "Bareta", category: "NSG-6" },
    { code: "DTW", name: "Datewas", category: "HG-3" },
    { code: "BLZ", name: "Budhlada", category: "NSG-5" },
    { code: "NPX", name: "Narinderapura", category: "NSG-6" },
    { code: "MSZ", name: "Mansa", category: "NSG-5" },
    { code: "SSZ", name: "Sadda Singhwala", category: "NSG-6" },
    { code: "KTKL", name: "Kotli Kalan Halt", category: "HG-3" },
    { code: "MAUR", name: "Maur", category: "NSG-5" },
    { code: "MASK", name: "Maisar Khana", category: "NSG-6" },
    { code: "KTF", name: "Kot Fateh", category: "NSG-6" },
    { code: "KZW", name: "Katar Singhwala", category: "NSG-6" },
  ],
  "MTC Section (NDLS-KZW)- 30 stations": [
    { code: "NDLS", name: "New Delhi", category: "NSG-1" },
    { code: "CSB", name: "Shivaji Bridge", category: "NSG-6" },
    { code: "TKJ", name: "Tilak Bridge", category: "NSG-6" },
    { code: "MWC", name: "Mandawali Chandra Vihar", category: "HG-2" },
    { code: "ANVR", name: "Anand Vihar Halt", category: "HG-2" },
    { code: "CNJ", name: "Chander Nagar Halt", category: "HG-3" },
    { code: "SBB", name: "Sahibabad", category: "NSG-4" },
    { code: "GZB", name: "Ghaziabad", category: "NSG-2" },
    { code: "GZN", name: "Naya Ghaziabad", category: "NSG-6" },
    { code: "GUH", name: "Guldhar", category: "NSG-6" },
    { code: "DXH", name: "Duhai Halt", category: "HG-3" },
    { code: "MUD", name: "Muradnagar", category: "NSG-6" },
    { code: "MDNR", name: "Modinagar", category: "NSG-4" },
    { code: "MUZ", name: "Mohiuddinpur", category: "NSG-6" },
    { code: "PRTP", name: "Partapur", category: "NSG-6" },
    { code: "MTC", name: "Meerut City", category: "NSG-3" },
    { code: "MUT", name: "Meerut Cantt.", category: "NSG-5" },
    { code: "PQY", name: "Pabli Khas", category: "NSG-6" },
    { code: "DRLA", name: "Daurala", category: "NSG-6" },
    { code: "SKF", name: "Sakhoti Tanda", category: "NSG-6" },
    { code: "KAT", name: "Khatauli", category: "NSG-5" },
    { code: "MSP", name: "Mansurpur", category: "NSG-6" },
    { code: "JDW", name: "Jarauda Nara", category: "NSG-6" },
    { code: "MOZ", name: "Muzaffarnagar", category: "NSG-3" },
    { code: "BMHR", name: "Baman Heri", category: "NSG-6" },
    { code: "RNA", name: "Rohana Kalan", category: "NSG-6" },
    { code: "DBD", name: "Deoband", category: "NSG-5" },
    { code: "THJ", name: "Talheri Buzurg", category: "NSG-6" },
    { code: "NGL", name: "Nagal", category: "NSG-6" },
    { code: "TPZ", name: "Tapri", category: "NSG-5" },
  ],
  "Major Stations (NDLS-DLI-NZM-ANVT)- 4 stations": [
    { code: "NDLS", name: "New Delhi", category: "NSG-1" },
    { code: "DLI", name: "Delhi Junction", category: "NSG-1" },
    { code: "NZM", name: "Hazrat Nizamuddin", category: "NSG-1" },
    { code: "ANVT", name: "Anand Vihar Terminal", category: "NSG-1" },
  ],
  "FDB Section (NDLS-PWL)- 11 stations": [
    { code: "NDLS", name: "New Delhi", category: "NSG-1" },
    { code: "CSB", name: "Shivaji Bridge", category: "NSG-6" },
    { code: "TKJ", name: "Tilak Bridge", category: "NSG-6" },
    { code: "NZM", name: "Hazrat Nizamuddin", category: "NSG-1" },
    { code: "OKA", name: "Okhla", category: "NSG-6" },
    { code: "TKD", name: "Tughlakabad", category: "NSG-5" },
    { code: "FDB", name: "Faridabad", category: "NSG-3" },
    { code: "FDN", name: "Faridabad New Town", category: "NSG-5" },
    { code: "BVH", name: "Ballabhgarh", category: "NSG-5" },
    { code: "AST", name: "Asaoti", category: "NSG-6" },
    { code: "PWL", name: "Palwal", category: "NSG-4" },
  ],
  "Ring Railway (NDLS-KZW)- 10 stations": [
    { code: "LPNR", name: "Lajpat Nagar", category: "NSG-6" },
    { code: "SWNR", name: "Sewa Nagar", category: "NSG-6" },
    { code: "LDCY", name: "Lodi Colony", category: "HG-3" },
    { code: "SOJ", name: "Sarojini Nagar", category: "NSG-6" },
    { code: "DSJ", name: "Delhi Safdarjung", category: "NSG-4" },
    { code: "BRSQ", name: "Brar Square", category: "NSG-6" },
    { code: "DLPI", name: "Delhi Inderpuri", category: "#N/A" },
    { code: "NRVR", name: "Naraina Vihar", category: "HG-3" },
    { code: "KRTN", name: "Kirti Nagar Halt", category: "HG-3" },
    { code: "PTNR", name: "Patel Nagar", category: "NSG-6" },
  ]
};
`;

code = code.replace("function HandoutWidget", mapping + "\nfunction HandoutWidget");
fs.writeFileSync(path, code);
console.log("inserted");
